### ISSUE TITLE
REQ: Add Facebook "__xts__"

### ISSUE THREAD

**Issue by rugabunda** [lifegpc/clearUrls#1]
Thank you for offering a more comprehensive block list.

Could you add for example, this common tracking code found in facebook links? Thank you!

https://www.facebook.com/druthers.net/videos/2380406625434986/?__xts__%5B0%5D=68.ARDiv9ThhkzpU7m7U1v_-OxLJ8b89BAWSoyLA11nuvCs9YmAbrFGdcM7jpM47FqRFKM395atOHXHxO9aJHD9JTjRFGaniYPU6OAfFxqwGQWkN95fbvtW1_2sbBie-nD2qFuatS0OQLeGRMRp4T7wGWFfEkPRw3s8ROyg2Xb3BsheaOUXh5_fy_3vzE0alqot7YtFOKHPI6o3vjXBf4__IqaKu_8kQ5nugxOJLZSExc_iPPVsdo6IgqMyLpqST5333FNcXjEZvZsLN-Y6QPocBBJ1mHsKARkV_12KeTpDOA2LtMFOnE-aR0pLCaSpfgY&__tn__=-R

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/156743734-38373514-6781-44d5-885a-73eeb25f7bea.png)
It seems already removed
